name: LaTeX CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  WORKDIR: coursework
  ROOT_TEX: coursework.tex
  OUTPUT_PDF: coursework/coursework.pdf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (опционально, но полезно) быстрый чек путей
      - name: Show .tex files (debug)
        run: |
          echo "WORKDIR=$WORKDIR"
          find . -maxdepth 3 -type f -name "*.tex" -printf "%P\n" | sort || true
          ls -la "$WORKDIR" || true

      # Собираем ИМЕННО pdflatex (как в твоём файле)
      - name: Compile LaTeX (pdflatex)
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: ${{ env.WORKDIR }}
          root_file: ${{ env.ROOT_TEX }}
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false   # поставь true, если нужен minted
          os: debian
          extra_system_packages: ""     # не нужно ничего дополнительно
          # latexmk сам сделает нужные проходы и вызовет biber при необходимости

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ${{ env.OUTPUT_PDF }}
