name: LaTeX CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Диагностика
      - name: Show structure (debug)
        run: |
          pwd
          ls -la
          echo "---- coursework ----"
          ls -la coursework || true
          echo "---- coursework/mainfiles ----"
          ls -la coursework/mainfiles || true

      # Проверяем наличие главного файла
      - name: Assert root file exists
        run: |
          test -f "coursework/coursework.tex" || { echo "::error file=coursework/coursework.tex::Root TeX not found"; exit 1; }

      # Сборка ВНУТРИ папки coursework (pdflatex)
      - name: Compile LaTeX (pdflatex in coursework/)
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: coursework     # <-- заходим в папку проекта
          root_file: coursework.tex         # <-- короткое имя файла
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false       # включи true, если используешь minted
          pre_compile: latexmk -C           # очистка мусора перед сборкой
          os: debian

      # Готовый PDF
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: coursework/coursework.pdf
          if-no-files-found: error
