name: LaTeX CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  WORKDIR: coursework
  ROOT_TEX: coursework.tex
  OUTPUT_PDF: coursework/coursework.pdf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Быстрый просмотр структуры
      - name: Show .tex files (debug)
        run: |
          echo "WORKDIR=$WORKDIR"
          find . -maxdepth 3 -type f -name "*.tex" -printf "%P\n" | sort || true
          ls -la "$WORKDIR" || true

      # Предупреждение, если в styles/ снова подключили babel/inputenc/fontenc
      - name: Guard against duplicate language packages
        run: |
          hits=$(grep -RInE '\usepackage(\[[^]]*\])?{(babel|inputenc|fontenc)}' coursework/styles || true)
          if [ -n "$hits" ]; then
            echo "::warning title=Duplicate language packages detected::"
            echo "$hits"
            echo "Языки/кодировки должны подключаться ОДИН РАЗ в coursework.tex"
          fi

      # Сборка pdflatex (как у тебя локально)
      - name: Compile LaTeX (pdflatex)
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: ${{ env.WORKDIR }}
          root_file: ${{ env.ROOT_TEX }}
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false     # включи true, если используешь minted
          pre_compile: latexmk -C         # очистить .aux/.bbl/.toc и пр.
          os: debian
          extra_system_packages: ""

      # Готовый PDF как артефакт
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ${{ env.OUTPUT_PDF }}
          if-no-files-found: error
