name: LaTeX CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  ROOT_TEX: coursework/coursework.tex
  OUTPUT_PDF: coursework/coursework.pdf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show .tex files (debug)
        run: |
          find . -maxdepth 3 -type f -name "*.tex" -printf "%P\n" | sort || true
          ls -la coursework || true
          ls -la coursework/mainfiles || true

      - name: Compile LaTeX (pdflatex from repo root)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ env.ROOT_TEX }}     # <— собираем из КОРНЯ
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false        # включи true, если нужен minted
          pre_compile: latexmk -C
          os: debian
          extra_system_packages: ""

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ${{ env.OUTPUT_PDF }}
          if-no-files-found: error
