name: LaTeX CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assert root file exists
        run: test -f "coursework/coursework.tex"

      - name: Compile LaTeX (pdflatex from repo root)
        uses: xu-cheng/latex-action@v4
        env:
          TEXINPUTS: ".:coursework:"   # чтобы \input{config.tex} находил coursework/config.tex
          BIBINPUTS: ".:coursework:"   # чтобы нашёл coursework.bib
          BSTINPUTS: ".:coursework:"
        with:
          root_file: |
            coursework/coursework.tex
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false   # включи true, если используешь minted
          os: debian

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: coursework/coursework.pdf
          if-no-files-found: error
