name: LaTeX CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Диагностика путей
      - name: Show .tex files (debug)
        run: |
          find . -maxdepth 3 -type f -name "*.tex" -printf "%P\n" | sort || true
          ls -la coursework || true
          ls -la coursework/mainfiles || true

      # Проверяем, что целевой файл есть
      - name: Assert root file exists
        run: |
          test -f "coursework/coursework.tex" || { echo "::error file=coursework/coursework.tex::Root TeX not found"; exit 1; }

      # Сборка pdflatex из КОРНЯ репозитория
      - name: Compile LaTeX (pdflatex)
        uses: xu-cheng/latex-action@v4
        with:
          # ВАЖНО: передаём root_file ЯВНО и мультистрокой — так экшен его гарантированно читает
          root_file: |
            coursework/coursework.tex
          work_in_root_file_dir: true     # компилировать в каталоге файла (./coursework)
          latexmk_use_xelatex: false
          latexmk_use_lualatex: false
          latexmk_shell_escape: false     # включи true, если нужен minted
          pre_compile: |
            latexmk -C
          os: debian

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: coursework/coursework.pdf
          if-no-files-found: error
